### ISSUE TITLE
[meta] Add topics to the repository

### ISSUE THREAD

**Issue by micalevisk** [LabO8/nestjs-s3#12]
to make this repository searchable from https://github.com/topics/nestjs and https://github.com/topics/nestjs-lib and https://github.com/topics/nest pages, you just need to add these three topics (`nestjs` & `nestjs-lib` & `nest`) :smile_cat: (and the `aws` would be good too I guess)

**Comment by micalevisk** [comment]
Also, you can add the docs site https://labo8.github.io/nestjs-s3 as the website of the repository so people could find them easily :fire:

**Comment by MartinAndreev** [comment]
Thank you for the suggestion. We will add them.

**Comment by MartinAndreev** [comment]
Done :)
