### ISSUE TITLE
bug: @InjectS3() typescript error

### ISSUE THREAD

**Issue by therosbif** [LabO8/nestjs-s3#35]
When trying to inject the S3 provider into a service I get the following error in VSCode:

`Unable to resolve signature of parameter decorator when called as an expression.   Argument of type 'undefined' is not assignable to parameter of type 'string | symbol'.`

Example reproduction:

```ts
import { InjectS3, S3 } from 'nestjs-s3';

@Injectable()
export class Service {
  constructor(
    @InjectS3() private readonly s3: S3,
  ) {}
}
```

**Comment by MartinAndreev** [comment]
Hey @therosbif  :) I think you are posting in the wrong repository. Think you want https://github.com/svtslv/nestjs-s3, but you can always try our implementation as well :)

**Comment by therosbif** [comment]
oh yes! sorry about the confusion.

Is it possible with this library with an S3 compatible API not hosted on AWS? I'm trying to make it work with DigitalOcean and I either get `Error: Region is missing` if i don't specify the `region` or `TypeError [ERR_INVALID_URL]: Invalid URL` when specifying a region

**Comment by MartinAndreev** [comment]
This one is build around the AWS sdk and I have not tested it with other services, but you can check the minio client as its compatible with most services that support s3. If you want, you can tryhttps://github.com/MartinAndreev/minio-nestjs-client which is a super simple wrapper for the official minio client
